/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windowssidepackage;

import QLTrungtamtinhoc.DNConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class qlLophoc extends javax.swing.JPanel {

    DefaultTableModel tb1;
    int idclass,idlec,idcou;
    int shift1,shift2;
    int slhv;
    String nameclass,nameroom,day1,day2,status;
    
    public qlLophoc(){
        try {
            initComponents();
            tb1 = (DefaultTableModel) jTable1.getModel();
            tb1.setRowCount(0);
            Statement st = DNConnect.getConnection();
            String sql = "SELECT * FROM information_class";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                String idclass1 = rs.getString("id_class");
                String nameclass1 = rs.getString("name_class");
                String idlecturer = String.valueOf(rs.getString("id_lecturer"));
                String classstart = rs.getString("class_start");
                String classfinish = rs.getString("class_finish");
                String idcourse = rs.getString("id_course");
                String nameroom1 = rs.getString("name_room");
                String daylearn1 = rs.getString("daylearn1");
                String shiftlearn1 = rs.getString("shiftlearn1");
                String daylearn2 = rs.getString("daylearn2");
                String shiftlearn2 = rs.getString("shiftlearn2");
                String SL_Student = rs.getString("SL_Student");
                String statusclass = rs.getString("status_class");
                
                tb1.addRow(new String[]{idclass1,nameclass1,idlecturer,classstart,classfinish,
                    idcourse,nameroom1,daylearn1,shiftlearn1,daylearn2,shiftlearn2,SL_Student,statusclass});
            }
        } catch (SQLException ex) {
            Logger.getLogger(qlLophoc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Insert = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jname = new javax.swing.JTextField();
        jstart = new javax.swing.JTextField();
        jfinish = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jidclass = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jidlec = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jidcou = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jslhv = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jstatus = new javax.swing.JTextField();
        jshift1 = new javax.swing.JComboBox();
        jday2 = new javax.swing.JComboBox();
        jshift2 = new javax.swing.JComboBox();
        jday1 = new javax.swing.JComboBox();
        jnameroom = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ LỚP HỌC");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã lớp học", "Tên lớp học", "Mã giáo viên", "Bắt đầu", "Kết thúc", "Mã khóa học", "Tên phòng", "Ngày học 1", "Ca học ngày 1", "Ngày học 2", "Ca học ngày 2", "SL Học viên", "Trạng thái"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Insert.setText("Thêm");
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });

        Delete.setText("Xóa");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        jLabel2.setText("Tên lớp");

        jLabel3.setText("Bắt đầu");

        jLabel4.setText("Kết thúc");

        jLabel5.setText("ID class");

        jLabel6.setText("Ngày học 1");

        jLabel7.setText("Ngày học 2");

        jLabel8.setText("ID giáo viên");

        jLabel9.setText("Ca học ngày 1 ");

        jLabel10.setText("Ca học ngày 2");

        jLabel11.setText("ID khóa học");

        jLabel12.setText("SL học viên");

        jLabel13.setText("Trạng thái");

        jshift1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));

        jday2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));

        jshift2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));

        jday1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));

        jLabel14.setText("Phòng học");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jname, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jfinish, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jday2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jstart, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel12)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel14))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jidcou, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                            .addComponent(jidlec, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                            .addComponent(jnameroom))
                                        .addGap(141, 142, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jidclass, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jslhv, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jshift1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jday1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jshift2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Insert)
                    .addComponent(Delete))
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Insert)
                    .addComponent(jLabel2)
                    .addComponent(jname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jstart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfinish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Delete)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(jidclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(jday1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jidlec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jshift1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jday2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jshift2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(jidcou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)
                                .addComponent(jslhv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jnameroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void InsertActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_InsertActionPerformed
    {//GEN-HEADEREND:event_InsertActionPerformed
        if(jidcou.getText().equals("")||jidlec.getText().equals("")||
                jname.getText().equals("")||jslhv.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Không được để trống");
        }else{
        
        idlec = Integer.valueOf(jidlec.getText());
        idcou = Integer.valueOf(jidcou.getText());
        nameclass = jname.getText();
        nameroom = jnameroom.getText();
        slhv = Integer.valueOf(jslhv.getText());
        shift1 = jshift1.getSelectedIndex()+1;
        shift2 = jshift2.getSelectedIndex()+1;
        day1 = jday1.getSelectedItem().toString();
        day2 = jday2.getSelectedItem().toString();
        status = jstatus.getText();
        String date1 = jstart.getText();
        String date2 = jfinish.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        int check1=0;
        int check2=0;
        try{
            java.util.Date jdate1 = sdf.parse(date1);
            java.sql.Date start = new java.sql.Date(jdate1.getTime());
            java.util.Date jdate2 = sdf.parse(date2);
            java.sql.Date finish = new java.sql.Date(jdate2.getTime());
            Connection cn = DNConnect.connected();
            Statement st1 = cn.createStatement();
            String sql1 = "select*from information_course";
            String sql2 = "select * from information_class";
            ResultSet rs = st1.executeQuery(sql1);
            while(rs.next()){
                int idcourse = rs.getInt("id_course");
                if(idcourse==idcou){
                    check1 = 1;
                }
            }
            ResultSet rs2 = st1.executeQuery(sql2);
            while(rs2.next()){
                String name2 = rs2.getString("name_class");
                int idlec2 = rs2.getInt("id_lecturer");
                String day12 = rs2.getString("daylearn1");
                int shift12 = rs2.getInt("shiftlearn1");
                String nameroom2 = rs2.getString("name_room");
                if(name2.equals(nameclass) && idlec==idlec2 && day12.equals(day1)
                        && shift12==shift1 && nameroom.equals(nameroom2)){
                    check2 ++;
                }
            }
            if(check1==0){
                JOptionPane.showMessageDialog(null, "Khóa học không tồn tại");
            }else{
                if(check2!=0){
                    JOptionPane.showMessageDialog(null, "Lớp học bị trùng");
                }else{
                    PreparedStatement st = null;
                    String sql = "insert into information_class (name_class,id_lecturer,id_course,"
                            + "class_start,class_finish,name_room,daylearn1,daylearn2,"
                            + "shiftlearn1,shiftlearn2,SL_student,status_class) value (?,?,?,?,?,?,?,?,?,?,?,?)";
                    st = cn.prepareStatement(sql);
                    st.setString(1, nameclass);
                    st.setInt(2, idlec);
                    st.setInt(3, idcou);
                    st.setDate(4, start);
                    st.setDate(5, finish);
                    st.setString(6, nameroom);
                    st.setString(7, day1);
                    st.setString(8, day2);
                    st.setInt(9, shift1);
                    st.setInt(10, shift2);
                    st.setInt(11, slhv);
                    st.setString(12, status);
                    st.execute();
                    JOptionPane.showMessageDialog(null, "Thêm thành công");
                }
            }
            cn.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Thêm lớp học thất bại");
        }
        }
    }//GEN-LAST:event_InsertActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_DeleteActionPerformed
    {//GEN-HEADEREND:event_DeleteActionPerformed
        String ID = jidclass.getText();
        if(ID.equals("")){
            JOptionPane.showMessageDialog(null, "Nhập id lớp học để xóa");
        }else{
        idclass = Integer.valueOf(jidclass.getText());
        try{
            Connection cn = DNConnect.connected();
            Statement st = cn.createStatement();
            String sql = "delete from information_class where id_class ="+idclass+"";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Xóa thành công");
            cn.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Xóa không thành công");
        }
        }
    }//GEN-LAST:event_DeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton Insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox jday1;
    private javax.swing.JComboBox jday2;
    private javax.swing.JTextField jfinish;
    private javax.swing.JTextField jidclass;
    private javax.swing.JTextField jidcou;
    private javax.swing.JTextField jidlec;
    private javax.swing.JTextField jname;
    private javax.swing.JTextField jnameroom;
    private javax.swing.JComboBox jshift1;
    private javax.swing.JComboBox jshift2;
    private javax.swing.JTextField jslhv;
    private javax.swing.JTextField jstart;
    private javax.swing.JTextField jstatus;
    // End of variables declaration//GEN-END:variables
}
